### ISSUE TITLE
Suggested changes to content?

### ISSUE THREAD

**Issue by temp1029** [raoulvdberge/refinedstorage-website#34]
If I have a content change suggestion, should I put it in here or somewhere else? Or would you rather not have those?

**Comment by raoulvdberge** [comment]
Sure, go ahead

**Comment by temp1029** [comment]
Can you add mouse controls for pattern grid? Left/right click for increase/decrease quantity and shift+right click to remove items.

**Comment by raoulvdberge** [comment]
Fixed.

See "Filter controls":

https://refinedstorage.raoulvdberge.com/wiki/interface

https://refinedstorage.raoulvdberge.com/wiki/pattern-grid
